FROM python:3.10-slim

WORKDIR /app

RUN mkdir static && mkdir templates && mkdir rdf && mkdir morph

COPY main.py .

COPY static/ ./static/

COPY templates/ ./templates/

COPY CSV/ .

COPY CSV/ ./CSV/

COPY morph/ .

COPY ../requirements.txt .

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

RUN pip install flask Flask-MySQL

RUN python3 -m morph_kgc configuration.ini

RUN cp ./KG.nt ./rdf/

CMD ["python","main.py"]


